config:
  credentials: []
  project_repos:
    github.com/EGI-Federation/cloud-info-provider:
      branch: master
      repo: https://github.com/EGI-Federation/cloud-info-provider.git
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EGI-Federation/cloud-info-provider git:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-buff-panda.sh
        container: qc.acc_chummy-pink-kingfisher
  QC.Doc:
    repos:
      github.com/EGI-Federation/cloud-info-provider find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-coral-dalmatian.sh
        container: qc.doc_shaggy-pear-orangutan
      github.com/EGI-Federation/cloud-info-provider git:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-maroon-earwig.sh
        container: qc.doc_wheezy-silver-fowl
      github.com/EGI-Federation/cloud-info-provider markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-olive-eel.sh
        container: qc.doc_cloudy-ochre-bird
  QC.Lic:
    repos:
      github.com/EGI-Federation/cloud-info-provider licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-wheat-bracke.sh
        container: qc.lic_lumpy-xanthic-warthog
  QC.Sec:
    repos:
      github.com/EGI-Federation/cloud-info-provider bandit:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-chocolate-fish.sh
        container: qc.sec_wiggy-yellow-sloth
  QC.Sty:
    repos:
      github.com/EGI-Federation/cloud-info-provider flake8:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-ruby-uguisu.sh
        container: qc.sty_bluesy-wisteria-raccoon
      github.com/EGI-Federation/cloud-info-provider jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-firebrick-chin.sh
        container: qc.sty_smelly-carmine-chin
  QC.Ver:
    repos:
      github.com/EGI-Federation/cloud-info-provider get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-rust-mongoose.sh
        container: qc.ver_craggy-corn-quail
timeout: 5400
